# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-03 18:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mybus', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='BusNo',
        ),
        migrations.AlterModelOptions(
            name='busno',
            options={'ordering': ['name'], 'verbose_name': 'BusNo', 'verbose_name_plural': 'BusNo'},
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='tags',
        ),
    ]
