# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-03 18:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mybus', '0003_auto_20160104_0008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businfo',
            name='url',
        ),
    ]
