# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-03 18:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mybus', '0005_auto_20160104_0027'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name=b'Bus Route')),
                ('is_public', models.BooleanField(default=True, verbose_name=b'Like my service')),
                ('date_created', models.DateTimeField(verbose_name=b'date created')),
                ('date_updated', models.DateTimeField(verbose_name=b'date updated')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BusInfo', to=settings.AUTH_USER_MODEL, verbose_name=b'owner')),
            ],
            options={
                'ordering': ['-date_created'],
                'verbose_name': 'BusInfo',
                'verbose_name_plural': 'BusInfos',
            },
        ),
        migrations.RenameModel(
            old_name='Tag',
            new_name='BusNo',
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='tags',
        ),
        migrations.AlterModelOptions(
            name='busno',
            options={'ordering': ['name'], 'verbose_name': 'BusNo', 'verbose_name_plural': 'BusNo'},
        ),
        migrations.DeleteModel(
            name='Bookmark',
        ),
    ]
