# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-03 19:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mybus', '0006_auto_20160104_0029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businfo',
            options={'ordering': ['-date_created'], 'verbose_name': 'BusInfo', 'verbose_name_plural': 'BusInfo'},
        ),
        migrations.AlterModelOptions(
            name='busno',
            options={'ordering': ['name'], 'verbose_name': 'BusNo', 'verbose_name_plural': 'BusNos'},
        ),
        migrations.AddField(
            model_name='businfo',
            name='description',
            field=models.TextField(blank=True, verbose_name=b'description'),
        ),
        migrations.AddField(
            model_name='businfo',
            name='url',
            field=models.CharField(default=datetime.datetime(2016, 1, 3, 19, 23, 5, 794000, tzinfo=utc), max_length=255, verbose_name=b'title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='businfo',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name=b'public'),
        ),
        migrations.AlterField(
            model_name='businfo',
            name='title',
            field=models.CharField(max_length=255, verbose_name=b'title'),
        ),
    ]
