# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-03 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybus', '0007_auto_20160104_0053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businfo',
            name='description',
        ),
        migrations.AlterField(
            model_name='businfo',
            name='title',
            field=models.CharField(max_length=255, verbose_name=b'Bus Info'),
        ),
        migrations.AlterField(
            model_name='businfo',
            name='url',
            field=models.CharField(max_length=255, verbose_name=b'Bus No'),
        ),
    ]
