# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-04 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybus', '0009_auto_20160104_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='businfo',
            name='latitude',
            field=models.CharField(default=0, max_length=255, verbose_name=b'Latitude'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businfo',
            name='longitude',
            field=models.CharField(default=0.1, max_length=255, verbose_name=b'Longitude'),
            preserve_default=False,
        ),
    ]
